"""
Financial Data Pipeline + Stylized Facts Evaluation
=======================================================
Fetches real market data and evaluates whether synthetic sequences
(generated by the DDPM) reproduce known statistical properties of
real financial returns — the "stylized facts" that any credible
market simulator must satisfy.

Stylized facts checked (Cont, 2001 — widely cited reference):
  1. Fat tails: excess kurtosis > 0 (returns aren't normally distributed)
  2. Volatility clustering: autocorrelation of |returns| decays slowly
  3. Near-zero autocorrelation of raw returns (market efficiency)
  4. Negative skew (crashes are sharper than rallies, typically)
"""

import numpy as np
import torch
import yfinance as yf


def fetch_real_returns(ticker: str = "^GSPC", period: str = "5y") -> np.ndarray:
    """
    Fetch daily log-returns for a given ticker.
    Default: S&P 500 index (^GSPC), 5 years of daily data.
    """
    data = yf.download(ticker, period=period, interval="1d", progress=False, auto_adjust=True)

    if data.empty:
        raise ValueError(f"No data returned for ticker {ticker}")

    close_prices = data["Close"].values.flatten()
    log_returns = np.diff(np.log(close_prices))

    return log_returns


def build_training_windows(
    log_returns: np.ndarray, sequence_length: int = 128, n_samples: int = 1000
) -> torch.Tensor:
    """
    Slice a long return series into overlapping windows for training.
    Each window is normalized independently (zero mean, unit variance)
    since DDPM training expects roughly standardized inputs.
    """
    n_available = len(log_returns) - sequence_length
    if n_available <= 0:
        raise ValueError("Not enough data for the requested sequence_length")

    windows = []
    # Sample random start indices with replacement if we need more
    # windows than unique non-overlapping slices allow
    indices = np.random.randint(0, n_available, size=n_samples)

    for start in indices:
        window = log_returns[start:start + sequence_length]
        window = (window - window.mean()) / (window.std() + 1e-8)
        windows.append(window)

    return torch.tensor(np.array(windows), dtype=torch.float32)


def compute_stylized_facts(sequences: np.ndarray) -> dict:
    """
    Compute the 4 key stylized facts for a batch of return sequences.
    `sequences` shape: (n_samples, sequence_length)

    Returns a dict suitable for JSON serialization and frontend display.
    """
    flat = sequences.flatten()

    # Fact 1: Kurtosis (excess kurtosis; normal distribution = 0)
    mean = flat.mean()
    std = flat.std() + 1e-8
    kurtosis = np.mean(((flat - mean) / std) ** 4) - 3

    # Fact 2: Skewness
    skewness = np.mean(((flat - mean) / std) ** 3)

    # Fact 3: Autocorrelation of raw returns at lag 1 (should be ~0)
    def autocorr(x, lag):
        n = len(x)
        x = x - x.mean()
        return np.sum(x[:n - lag] * x[lag:]) / (np.sum(x ** 2) + 1e-8)

    raw_acf_lag1 = np.mean([autocorr(seq, 1) for seq in sequences])

    # Fact 4: Volatility clustering — autocorrelation of ABSOLUTE returns
    # at several lags (should stay positive longer than raw returns)
    abs_acf = {}
    for lag in [1, 5, 10, 20]:
        abs_sequences = np.abs(sequences)
        acf_vals = [autocorr(seq, lag) for seq in abs_sequences if len(seq) > lag]
        abs_acf[f"lag_{lag}"] = round(float(np.mean(acf_vals)), 4) if acf_vals else None

    # Volatility clustering is judged on the AVERAGE positive autocorrelation
    # across lags, not a single lag threshold — real markets show persistent
    # (if noisy) positive autocorrelation in |returns| across many lags.
    valid_acf_values = [v for v in abs_acf.values() if v is not None]
    avg_abs_acf = float(np.mean(valid_acf_values)) if valid_acf_values else 0.0

    return {
        "kurtosis": round(float(kurtosis), 4),
        "kurtosis_interpretation": "fat-tailed (realistic)" if kurtosis > 0.5 else "too normal (unrealistic)",
        "skewness": round(float(skewness), 4),
        "raw_return_autocorr_lag1": round(float(raw_acf_lag1), 4),
        "raw_autocorr_interpretation": "near zero (realistic)" if abs(raw_acf_lag1) < 0.1 else "too correlated (unrealistic)",
        "volatility_clustering_acf": abs_acf,
        "avg_volatility_clustering": round(avg_abs_acf, 4),
        "volatility_clustering_interpretation": (
            "present (realistic)" if avg_abs_acf > 0.02 else "absent (unrealistic)"
        ),
    }


def compute_histogram(sequences: np.ndarray, n_bins: int = 40) -> dict:
    """Compute a histogram of all return values for frontend distribution plotting."""
    flat = sequences.flatten()
    counts, bin_edges = np.histogram(flat, bins=n_bins)
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

    return {
        "bin_centers": [round(float(b), 4) for b in bin_centers],
        "counts": [int(c) for c in counts],
    }