"""add data_source and ticker fields

Revision ID: 4772117b4af5
Revises: d932a108565f
Create Date: 2026-07-12 20:39:53.234900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4772117b4af5'
down_revision: Union[str, None] = 'd932a108565f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('experiments', sa.Column('data_source', sa.String(), nullable=False, server_default='synthetic'))
    op.add_column('experiments', sa.Column('ticker', sa.String(), nullable=True, server_default='^GSPC'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'ticker')
    op.drop_column('experiments', 'data_source')
    # ### end Alembic commands ###
