"""add model_weights_path

Revision ID: d932a108565f
Revises: e457ac8a9205
Create Date: 2026-07-12 14:51:53.512606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd932a108565f'
down_revision: Union[str, None] = 'e457ac8a9205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('model_weights_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'model_weights_path')
    # ### end Alembic commands ###
